### PR TITLE
Add Jekyll Feature

### PR DESCRIPTION
**Pull request by koumaza**
If you like~

### CODE REVIEW

**Comment by koumaza** [comment]
Preview here: https://imgur.com/a/uudmMvV

**Comment by yuk7** [comment]
Almost ok 
LGTM👍

**Comment by yuk7** [comment]
LGTM👍
Why do you revert commit?

**Comment by koumaza** [comment]
Ahh, I was trying it on another Repo before committing here,
so I purged it and force push it because it had a configuration left.

**Review by yuk7 — APPROVED** [review]

**Comment by yuk7** [comment]
Ok. arigato

**Comment by yuk7** [comment]
I configure it to GitHub Pages temporarily.
After confirmation, merge it into main branch.

https://wsldl-pg.github.io/docs

**Comment by koumaza** [comment]
Yeah, it's better to check and then merge

**Pull request merged**
